"""Topic 01 — Core mechanics.

Read `lessons/01-core-mechanics.md` first, then implement each function below.
Delete the `raise NotImplementedError` line and write the real thing.

    uv run pytest phases/01-foundations/part-a/tests/test_01_core_mechanics.py
"""

from __future__ import annotations

# A chat message as every provider API models it: a dict with "role" and "content".
# You will see this exact shape from Phase 2 onward.
Message = dict[str, str]


def unique_preserving_order(items: list[str]) -> list[str]:
    """Drop duplicates while keeping first-seen order.

    `list(set(items))` would dedupe but scramble the order — sets have none.
    You need two containers: one to remember what you have seen, one to record
    the answer. Pick each for what it is good at.

    Args:
        items: Values that may contain duplicates.

    Returns:
        The unique values, in the order they first appeared.
    """
    raise NotImplementedError("Exercise 1.1")


def count_roles(messages: list[Message]) -> dict[str, int]:
    """Count how many messages each role sent.

    The dict-accumulation idiom from the lesson. Assume every message has a
    "role" key — if one does not, that is a bug and should raise, not be
    silently skipped.

    Args:
        messages: Chat messages, each with at least a "role" key.

    Returns:
        Role -> number of messages with that role. Empty input, empty dict.
    """
    raise NotImplementedError("Exercise 1.2")


def last_n_messages(messages: list[Message], n: int) -> list[Message]:
    """Return the most recent `n` messages, oldest first.

    This is conversation-history trimming, which every chat client does. Mind
    the `-0` trap from the lesson: `messages[-n:]` returns *everything* when
    `n` is 0. Handle `n <= 0` explicitly.

    Args:
        messages: The full history, oldest first.
        n: How many recent messages to keep.

    Returns:
        At most `n` messages, still oldest first. Empty list if `n <= 0`.
    """
    raise NotImplementedError("Exercise 1.3")


def describe_usage(prompt_tokens: int, completion_tokens: int, usd_per_million: float) -> str:
    """Format a token-usage line for a terminal report.

    Exact expected output for (1000, 500, 3.0):

        1,000 in + 500 out = 1,500 tokens ($0.0045)

    Thousands separators on the counts, four decimal places on the dollar
    amount. Cost is (total tokens / 1_000_000) * usd_per_million.

    Args:
        prompt_tokens: Tokens sent to the model.
        completion_tokens: Tokens generated by the model.
        usd_per_million: Price per million tokens, in dollars.

    Returns:
        The formatted single-line summary.
    """
    raise NotImplementedError("Exercise 1.4")


def is_blank(value: str | None) -> bool:
    """Is this value missing, empty, or only whitespace?

    Exercises truthiness vs `is None`. Note that `"0"` is a real string and is
    NOT blank, but `"   "` is. Get the order of your checks right.

    Args:
        value: A string that may be None.

    Returns:
        True if value is None, empty, or whitespace-only.
    """
    raise NotImplementedError("Exercise 1.5")


def merge_config(defaults: dict[str, str], overrides: dict[str, str]) -> dict[str, str]:
    """Layer `overrides` on top of `defaults` without touching either input.

    The test asserts that `defaults` is unchanged afterwards. `.update()` will
    fail that assertion; the lesson shows what to use instead.

    Args:
        defaults: Base configuration.
        overrides: Values that win on conflict.

    Returns:
        A new dict containing both, overrides taking precedence.
    """
    raise NotImplementedError("Exercise 1.6")


def split_by_role(messages: list[Message], role: str) -> tuple[list[Message], list[Message]]:
    """Partition messages into (matching, everything else).

    Returning a tuple is how Python does fixed-shape multiple returns — the
    caller unpacks it: `mine, theirs = split_by_role(...)`. Both lists keep
    their original relative order.

    Args:
        messages: Chat messages, each with a "role" key.
        role: The role to select on.

    Returns:
        A 2-tuple: (messages with that role, all the others).
    """
    raise NotImplementedError("Exercise 1.7")
